[package]
name = "demo_project"
version = "0.1.0"
authors = ["saisrikanthmadugula <64686118+saisrikanthmadugula@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
